language: python
python:
  - 3.4
  - 3.5
matrix:
  fast_finish: true
sudo: false
cache: pip
install:
  - pip install coveralls flake8 pep257
  - npm install -g eslint
  - gem install rubocop scss_lint
script:
  - flake8
  - pep257
  - coverage run --source=farcy setup.py test
after_success: coveralls
