language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy
  - pypy3
matrix:
  allow_failures:
  - python: nightly
  - python: pypy
  - python: pypy3
sudo: false
install:
  - pip install coveralls flake8 pep257
  - npm install eslint
  - gem install rubocop
script:
  - flake8 farcy
  - pep257 farcy
  - coverage run --source=farcy setup.py test
after_success: coveralls
